### ISSUE TITLE
Log all user claims?

### ISSUE THREAD

**Issue by lonix1** [intility/serilog-enrichers-azureclaims#14]
README shows to do this:
```cs
.Enrich.WithCustomClaim("AnyExistingClaim")
```

Is it possible to log all claims from `ControllerBase.User.Claims`?

**Comment by loekensgard** [comment]
Hi @lonix1,

The functionality from the NuGet package 'Serilog.Enrichers.Claims' will only retrieve one claim at a time by using the [FindFirstValue](https://github.com/intility/serilog-enrichers-azureclaims/blob/main/src/Serilog.Enrichers.Claims/Enrichers/ClaimEnricher.cs#L107) method. 

I'm not sure if it is desirable to print everything in a token instead of enriching the log with multiple properties, such as:

```csharp
.Enrich.WithCustomClaim("CustomProperty1")
.Enrich.WithCustomClaim("CustomProperty2")
.Enrich.WithCustomClaim("CustomProperty3")
.Enrich.WithCustomClaim("CustomProperty4")
```
 
If you use EntraID to generate the access tokens, the other package 'Serilog.Enrichers.AzureClaims' will already include the most commonly used claims.
